# Generated by Django 4.2.2 on 2024-05-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='punteggio_squadra',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
