# Generated by Django 4.2.2 on 2024-05-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_punteggio_squadra_alter_evento_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='punteggio_squadra',
        ),
    ]
