# Generated by Django 4.2.1 on 2023-06-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_cartitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
