# Generated by Django 4.2.1 on 2023-06-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_delete_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_status",
            field=models.CharField(
                choices=[("not_shipped", "Non spedito"), ("shipped", "Spedito")],
                default="not_shipped",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("processing", "In elaborazione")], max_length=255
            ),
        ),
    ]
