# Generated by Django 4.2.2 on 2024-05-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_evento_punteggio_squadra'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='punteggio_squadra',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
