# Generated by Django 4.2.2 on 2024-07-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_evento_punteggio_squadra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('punti', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Squadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('punti', models.IntegerField(default=0)),
            ],
        ),
    ]
