# Generated by Django 4.2.2 on 2024-07-04 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_azione_squadra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadra',
            name='punti',
        ),
        migrations.CreateModel(
            name='SquadraAzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completata', models.BooleanField(default=False)),
                ('azione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.azione')),
                ('squadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.squadra')),
            ],
        ),
    ]
