# Generated by Django 4.2.1 on 2023-06-17 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="billing_address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="shipping_address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
