# Generated by Django 4.2.2 on 2024-07-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_squadra_punti_squadraazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='azione',
            name='azione_esclusiva',
            field=models.BooleanField(default=False),
        ),
    ]
